"""Hardware-bound license verification package."""

from skyadmin_pro.services.license.machine import get_machine_id
from skyadmin_pro.services.license.online import (
    _get_last_sync_time,
    get_daily_sync_status,
    is_daily_sync_stale,
    requires_online_check,
)
from skyadmin_pro.services.license.verify import (
    _is_repair_activation,
    _parse_expiry,
    _payload_of,
    _read_license_payload,
    _self_heal_license,
    _verify_integrity,
    activation_request_message,
    available_update,
    banned_machines,
    check_activation_usable,
    check_for_updates,
    fetch_revocations,
    find_license_file,
    generate_license,
    generate_passcode,
    is_newer_version,
    license_expiry_text,
    license_remaining_days,
    license_status_text,
    license_time_left_text,
    mark_used,
    read_update_info,
    report_activation_claim,
    revoked_nonces,
    revoked_passcodes,
    save_license_file,
    used_nonces,
    verify_key_text,
    verify_license,
    verify_passcode,
)

__all__ = [
    "activation_request_message",
    "available_update",
    "banned_machines",
    "check_activation_usable",
    "check_for_updates",
    "fetch_revocations",
    "find_license_file",
    "generate_license",
    "generate_passcode",
    "get_daily_sync_status",
    "get_machine_id",
    "is_daily_sync_stale",
    "is_newer_version",
    "license_expiry_text",
    "license_remaining_days",
    "license_status_text",
    "license_time_left_text",
    "mark_used",
    "read_update_info",
    "report_activation_claim",
    "requires_online_check",
    "revoked_nonces",
    "revoked_passcodes",
    "save_license_file",
    "used_nonces",
    "verify_key_text",
    "verify_license",
    "verify_passcode",
    "_get_last_sync_time",
    "_parse_expiry",
    "_payload_of",
    "_read_license_payload",
    "_self_heal_license",
    "_verify_integrity",
]
