SCHEMA_SQL_PART_3 = (
    "CREATE INDEX IF NOT EXISTS idx_supplier_payments_due ON supplier_payments(due_date);\n"
    "CREATE INDEX IF NOT EXISTS idx_supplier_payments_paid ON supplier_payments(paid);\n"
    "CREATE INDEX IF NOT EXISTS idx_supplier_payments_unpaid_due\n"
    "    ON supplier_payments(due_date, supplier_id)\n"
    "    WHERE paid = 0\n"
    "      AND due_date IS NOT NULL\n"
    "      AND trim(due_date) != '';\n"
    "CREATE INDEX IF NOT EXISTS idx_renewals_service ON service_renewals(service_id);\n"
    "CREATE INDEX IF NOT EXISTS idx_renewals_client ON service_renewals(client_id);\n"
    "\n"
    "CREATE TABLE IF NOT EXISTS supplier_services (\n"
    "    id            INTEGER PRIMARY KEY AUTOINCREMENT,\n"
    "    supplier_id   INTEGER NOT NULL,\n"
    "    company_name  TEXT    NOT NULL,\n"
    "    service_type  TEXT    NOT NULL,\n"
    "    expiry_date   TEXT,\n"
    "    notes         TEXT,\n"
    "    created_at    TEXT    NOT NULL DEFAULT (datetime('now', 'localtime')),\n"
    "    FOREIGN KEY (supplier_id) REFERENCES suppliers(id) ON DELETE CASCADE\n"
    ");\n"
    "CREATE INDEX IF NOT EXISTS idx_supplier_services_supplier ON supplier_services(supplier_id);\n"
    "CREATE INDEX IF NOT EXISTS idx_client_months_month ON client_months(month_key);\n"
    "CREATE INDEX IF NOT EXISTS idx_checklist_templates_name ON checklist_templates(name);\n"
    "\n"
    "CREATE TABLE IF NOT EXISTS pricing_matrix (\n"
    "    id                  INTEGER PRIMARY KEY AUTOINCREMENT,\n"
    "    service_type        TEXT NOT NULL DEFAULT 'General',\n"
    "    transaction_range   TEXT NOT NULL,\n"
    "    monthly_fee         INTEGER,\n"
    "    annual_fee          INTEGER,\n"
    "    sla_hours           INTEGER,\n"
    "    headcount           INTEGER,\n"
    "    required_docs       TEXT,\n"
    "    UNIQUE(service_type, transaction_range)\n"
    ");\n"
    "\n"
    "CREATE TABLE IF NOT EXISTS tax_cycle_log (\n"
    "    id          INTEGER PRIMARY KEY AUTOINCREMENT,\n"
    "    client_id   INTEGER,\n"
    "    field       TEXT,\n"
    "    old_value   TEXT,\n"
    "    new_value   TEXT,\n"
    "    changed_at  TEXT DEFAULT (datetime('now', 'localtime')),\n"
    "    FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE SET NULL\n"
    ");\n"
    "CREATE INDEX IF NOT EXISTS idx_tax_cycle_log_client ON tax_cycle_log(client_id);\n"
    "\n"
    "CREATE TABLE IF NOT EXISTS financial_documents (\n"
    "    id              INTEGER PRIMARY KEY AUTOINCREMENT,\n"
    "    client_id       INTEGER,\n"
    "    category        TEXT NOT NULL,\n"
    "    subcategory     TEXT,\n"
    "    file_name       TEXT NOT NULL,\n"
    "    file_path       TEXT NOT NULL,\n"
    "    stored_path     TEXT,\n"
    "    amount          TEXT,\n"
    "    doc_date        TEXT,\n"
    "    description     TEXT,\n"
    "    created_at      TEXT NOT NULL DEFAULT (datetime('now', 'localtime')),\n"
    "    FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE SET NULL\n"
    ");\n"
    "CREATE INDEX IF NOT EXISTS idx_financial_docs_client ON financial_documents(client_id);\n"
    "CREATE INDEX IF NOT EXISTS idx_financial_docs_category ON financial_documents(category);\n"
    "\n"
    "CREATE TABLE IF NOT EXISTS office_contacts (\n"
    "    id              INTEGER PRIMARY KEY AUTOINCREMENT,\n"
    "    name            TEXT    NOT NULL,\n"
    "    role_title      TEXT,\n"
    "    organization    TEXT,\n"
    "    department      TEXT,\n"
)
