SCHEMA_SQL_PART_2 = (
    "CREATE TABLE IF NOT EXISTS pipeline_items (\n"
    "    id         INTEGER PRIMARY KEY AUTOINCREMENT,\n"
    "    client_id  INTEGER NOT NULL,\n"
    "    service    TEXT    NOT NULL,\n"
    "    step       INTEGER NOT NULL DEFAULT 1,\n"
    "    step_date  TEXT,\n"
    "    notes      TEXT,\n"
    "    created_at TEXT    NOT NULL DEFAULT (datetime('now', 'localtime')),\n"
    "    updated_at TEXT    NOT NULL DEFAULT (datetime('now', 'localtime')),\n"
    "    FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE CASCADE\n"
    ");\n"
    "\n"
    "CREATE TABLE IF NOT EXISTS suppliers (\n"
    "    id           INTEGER PRIMARY KEY AUTOINCREMENT,\n"
    "    name         TEXT    NOT NULL UNIQUE COLLATE NOCASE,\n"
    "    company_name TEXT,\n"
    "    contact      TEXT,\n"
    "    notes        TEXT,\n"
    "    created_at   TEXT    NOT NULL DEFAULT (datetime('now', 'localtime')),\n"
    "    updated_at   TEXT    NOT NULL DEFAULT (datetime('now', 'localtime'))\n"
    ");\n"
    "\n"
    "CREATE TABLE IF NOT EXISTS supplier_payments (\n"
    "    id          INTEGER PRIMARY KEY AUTOINCREMENT,\n"
    "    supplier_id INTEGER NOT NULL,\n"
    "    client_id   INTEGER,\n"
    "    amount      TEXT,\n"
    "    due_date    TEXT,\n"
    "    paid        INTEGER NOT NULL DEFAULT 0,\n"
    "    paid_date   TEXT,\n"
    "    notes       TEXT,\n"
    "    created_at  TEXT    NOT NULL DEFAULT (datetime('now', 'localtime')),\n"
    "    updated_at  TEXT    NOT NULL DEFAULT (datetime('now', 'localtime')),\n"
    "    FOREIGN KEY (supplier_id) REFERENCES suppliers(id) ON DELETE CASCADE,\n"
    "    FOREIGN KEY (client_id)   REFERENCES clients(id)   ON DELETE SET NULL\n"
    ");\n"
    "\n"
    "CREATE TABLE IF NOT EXISTS service_renewals (\n"
    "    id              INTEGER PRIMARY KEY AUTOINCREMENT,\n"
    "    service_id      INTEGER NOT NULL,\n"
    "    client_id       INTEGER,\n"
    "    document_type   TEXT,\n"
    "    previous_expiry TEXT,\n"
    "    new_expiry      TEXT    NOT NULL,\n"
    "    note            TEXT,\n"
    "    needs_documents INTEGER NOT NULL DEFAULT 1,\n"
    "    task_id         INTEGER,\n"
    "    created_at      TEXT    NOT NULL DEFAULT (datetime('now', 'localtime')),\n"
    "    FOREIGN KEY (service_id) REFERENCES documents(id) ON DELETE CASCADE,\n"
    "    FOREIGN KEY (client_id) REFERENCES clients(id)   ON DELETE CASCADE,\n"
    "    FOREIGN KEY (task_id)    REFERENCES tasks(id)    ON DELETE CASCADE\n"
    ");\n"
    "\n"
    "CREATE TABLE IF NOT EXISTS settings (\n"
    "    key    TEXT PRIMARY KEY,\n"
    "    value  TEXT\n"
    ");\n"
    "\n"
    "CREATE INDEX IF NOT EXISTS idx_tasks_status ON tasks(status);\n"
    "CREATE INDEX IF NOT EXISTS idx_tasks_completed_at ON tasks(completed_at);\n"
    "CREATE INDEX IF NOT EXISTS idx_tasks_client ON tasks(client_id);\n"
    "CREATE INDEX IF NOT EXISTS idx_tasks_pipeline ON tasks(pipeline_item_id);\n"
    "CREATE INDEX IF NOT EXISTS idx_tasks_source_document ON tasks(source_document_id);\n"
    "CREATE INDEX IF NOT EXISTS idx_documents_expiry ON documents(expiry_date);\n"
    "CREATE INDEX IF NOT EXISTS idx_documents_client ON documents(client_id);\n"
    "CREATE INDEX IF NOT EXISTS idx_documents_payment_date ON documents(payment_date);\n"
    "CREATE INDEX IF NOT EXISTS idx_documents_start_date ON documents(start_date);\n"
    "CREATE INDEX IF NOT EXISTS idx_pipeline_client ON pipeline_items(client_id);\n"
    "CREATE INDEX IF NOT EXISTS idx_courier_logs_client ON courier_logs(client_id);\n"
)
