SCHEMA_SQL_PART_0 = (
    "\n"
    "PRAGMA foreign_keys = ON;\n"
    "\n"
    "CREATE TABLE IF NOT EXISTS clients (\n"
    "    id                    INTEGER PRIMARY KEY AUTOINCREMENT,\n"
    "    name                  TEXT    NOT NULL UNIQUE COLLATE NOCASE,\n"
    "    company_name          TEXT,\n"
    "    contact_name          TEXT,\n"
    "    email                 TEXT,\n"
    "    status                TEXT    NOT NULL DEFAULT 'active',\n"
    "    notes                 TEXT,\n"
    "    registration_number   TEXT,\n"
    "    director              TEXT,\n"
    "    contact_number        TEXT,\n"
    "    registered_capital    TEXT,\n"
    "    vat_registration      TEXT,\n"
    "    business_address      TEXT,\n"
    "    business_objectives   TEXT,\n"
    "    tax_id                TEXT,\n"
    "    ird_password          TEXT,\n"
    "    vat_registered        INTEGER DEFAULT 0,\n"
    "    vat_registered_date   TEXT,\n"
    "    service_type          TEXT,\n"
    "    num_transactions      TEXT,\n"
    "    service_fee           TEXT,\n"
    "    payment_status        TEXT,\n"
    "    sla                   TEXT,\n"
    "    headcount             INTEGER,\n"
    "    fs_status             TEXT    DEFAULT 'Not Applicable',\n"
    "    pnd1_status           TEXT    DEFAULT 'Not Applicable',\n"
    "    pnd3_status           TEXT    DEFAULT 'Not Applicable',\n"
    "    pnd53_status          TEXT    DEFAULT 'Not Applicable',\n"
    "    pp30_status           TEXT    DEFAULT 'Not Applicable',\n"
    "    pnd90_status          TEXT    DEFAULT 'Not Applicable',\n"
    "    pnd91_status          TEXT    DEFAULT 'Not Applicable',\n"
    "    pnd51_status          TEXT    DEFAULT 'Not Applicable',\n"
    "    pnd50_status          TEXT    DEFAULT 'Not Applicable',\n"
    "    audit_status          TEXT    DEFAULT 'Not Applicable',\n"
    "    vo_address            TEXT,\n"
    "    vo_service_provider   TEXT,\n"
    "    vo_renewal_date       TEXT,\n"
    "    csh_service_provider  TEXT,\n"
    "    csh_renewal_date      TEXT,\n"
    "    shareholder_info      TEXT,\n"
    "    global_id             TEXT UNIQUE,\n"
    "    group_id              INTEGER,\n"
    "    deleted_at            TEXT,\n"
    "    created_at            TEXT    NOT NULL DEFAULT (datetime('now', 'localtime')),\n"
    "    updated_at            TEXT    NOT NULL DEFAULT (datetime('now', 'localtime'))\n"
    ");\n"
    "\n"
    "CREATE TABLE IF NOT EXISTS tasks (\n"
    "    id            INTEGER PRIMARY KEY AUTOINCREMENT,\n"
    "    client_id     INTEGER,\n"
    "    title         TEXT    NOT NULL,\n"
    "    description   TEXT,\n"
    "    status        TEXT    NOT NULL DEFAULT 'pending'\n"
    "                  CHECK (status IN ('pending', 'completed')),\n"
    "    category      TEXT    NOT NULL DEFAULT 'general',\n"
    "    due_date      TEXT,\n"
    "    completed_at  TEXT,\n"
    "    pipeline_item_id INTEGER,\n"
    "    pipeline_step    INTEGER,\n"
    "    source_document_id INTEGER,\n"
    "    parent_task_id INTEGER,\n"
    "    global_id     TEXT UNIQUE,\n"
    "    deleted_at    TEXT,\n"
    "    created_at    TEXT    NOT NULL DEFAULT (datetime('now', 'localtime')),\n"
    "    updated_at    TEXT    NOT NULL DEFAULT (datetime('now', 'localtime')),\n"
    "    FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE SET NULL,\n"
    "    FOREIGN KEY (parent_task_id) REFERENCES tasks(id) ON DELETE SET NULL\n"
    ");\n"
    "\n"
    "CREATE TABLE IF NOT EXISTS documents (\n"
)
