SCHEMA_SQL_PART_5 = (
    "\n"
    "-- Additional performance indexes\n"
    "CREATE INDEX IF NOT EXISTS idx_clients_status ON clients(status);\n"
    "CREATE INDEX IF NOT EXISTS idx_tasks_due_date ON tasks(due_date);\n"
    "CREATE INDEX IF NOT EXISTS idx_tasks_category ON tasks(category);\n"
    "CREATE INDEX IF NOT EXISTS idx_documents_type ON documents(document_type);\n"
    "CREATE INDEX IF NOT EXISTS idx_documents_progress ON documents(progress);\n"
    "CREATE INDEX IF NOT EXISTS idx_documents_paid ON documents(paid);\n"
    "CREATE INDEX IF NOT EXISTS idx_documents_unpaid_overdue\n"
    "    ON documents(payment_date, document_type, client_id)\n"
    "    WHERE client_id IS NOT NULL\n"
    "      AND COALESCE(paid, 0) = 0\n"
    "      AND payment_date IS NOT NULL\n"
    "      AND trim(payment_date) != '';\n"
    "CREATE INDEX IF NOT EXISTS idx_documents_ongoing_service\n"
    "    ON documents(document_type, client_id)\n"
    "    WHERE client_id IS NOT NULL\n"
    "      AND progress = 'Ongoing';\n"
    "CREATE INDEX IF NOT EXISTS idx_pipeline_step ON pipeline_items(step);\n"
    "CREATE INDEX IF NOT EXISTS idx_pipeline_updated ON pipeline_items(updated_at);\n"
    "CREATE INDEX IF NOT EXISTS idx_supplier_services_type ON supplier_services(service_type);\n"
    "CREATE INDEX IF NOT EXISTS idx_supplier_services_expiry ON supplier_services(expiry_date);\n"
    "CREATE INDEX IF NOT EXISTS idx_supplier_payments_supplier ON supplier_payments(supplier_id);\n"
    "CREATE INDEX IF NOT EXISTS idx_notebook_client ON notebook_entries(client_id);\n"
    "CREATE INDEX IF NOT EXISTS idx_tax_cycle_changed ON tax_cycle_log(changed_at);\n"
    "CREATE INDEX IF NOT EXISTS idx_courier_date ON courier_logs(date_sent);\n"
    "\n"
    "-- P4.1: sync conflict audit log (last-write-wins skips)\n"
    "CREATE TABLE IF NOT EXISTS sync_conflicts (\n"
    "    id                  INTEGER PRIMARY KEY AUTOINCREMENT,\n"
    "    table_name          TEXT    NOT NULL,\n"
    "    global_id           TEXT    NOT NULL,\n"
    "    direction           TEXT    NOT NULL,\n"
    "    local_updated_at    TEXT,\n"
    "    remote_updated_at   TEXT,\n"
    "    logged_at           TEXT    NOT NULL DEFAULT (datetime('now', 'localtime'))\n"
    ");\n"
    "CREATE INDEX IF NOT EXISTS idx_sync_conflicts_logged ON sync_conflicts(logged_at);\n"
    "\n"
    "-- Client grouping (table only; the group_id column + index are owned by\n"
    "-- migration m009 because _initialize replays this file BEFORE min_version=2\n"
    "-- migrations run). Sync columns (global_id / updated_at / deleted_at) are\n"
    "-- added by m011 — clients.group_id stays local; membership syncs via\n"
    "-- group_global_id on the wire.\n"
    "CREATE TABLE IF NOT EXISTS client_groups (\n"
    "    id          INTEGER PRIMARY KEY AUTOINCREMENT,\n"
    "    name        TEXT    NOT NULL UNIQUE COLLATE NOCASE,\n"
    "    color       TEXT,\n"
    "    created_at  TEXT    NOT NULL DEFAULT (datetime('now', 'localtime'))\n"
    ");\n"
    "\n"
    "-- FTS5 client search (Phase 10.1). Kept in base schema so FRESH installs get\n"
    "-- MATCH search immediately; legacy DBs are backfilled by m001.\n"
    "-- All statements are IF NOT EXISTS, so replay over migrated DBs is a no-op.\n"
    "CREATE VIRTUAL TABLE IF NOT EXISTS clients_fts USING fts5(\n"
    "    name, contact_name, email, tokenize='unicode61'\n"
    ");\n"
    "CREATE TRIGGER IF NOT EXISTS clients_fts_ai AFTER INSERT ON clients BEGIN\n"
    "    INSERT INTO clients_fts(rowid, name, contact_name, email)\n"
    "    VALUES (new.id, COALESCE(new.name,''), COALESCE(new.contact_name,''), COALESCE(new.email,''));\n"
    "END;\n"
    "CREATE TRIGGER IF NOT EXISTS clients_fts_ad AFTER DELETE ON clients BEGIN\n"
    "    DELETE FROM clients_fts WHERE rowid = old.id;\n"
    "END;\n"
    "CREATE TRIGGER IF NOT EXISTS clients_fts_au AFTER UPDATE ON clients BEGIN\n"
    "    DELETE FROM clients_fts WHERE rowid = old.id;\n"
    "    INSERT INTO clients_fts(rowid, name, contact_name, email)\n"
    "    VALUES (new.id, COALESCE(new.name,''), COALESCE(new.contact_name,''), COALESCE(new.email,''));\n"
    "END;\n"
)
