SCHEMA_SQL_PART_4 = (
    "    phone           TEXT,\n"
    "    email           TEXT,\n"
    "    line_id         TEXT,\n"
    "    category        TEXT    NOT NULL DEFAULT 'Office',\n"
    "    client_id       INTEGER,\n"
    "    notes           TEXT,\n"
    "    is_favorite     INTEGER NOT NULL DEFAULT 0,\n"
    "    global_id       TEXT UNIQUE,\n"
    "    deleted_at      TEXT,\n"
    "    created_at      TEXT    NOT NULL DEFAULT (datetime('now', 'localtime')),\n"
    "    updated_at      TEXT    NOT NULL DEFAULT (datetime('now', 'localtime')),\n"
    "    FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE SET NULL\n"
    ");\n"
    "CREATE INDEX IF NOT EXISTS idx_office_contacts_name ON office_contacts(name);\n"
    "CREATE INDEX IF NOT EXISTS idx_office_contacts_category ON office_contacts(category);\n"
    "\n"
    "CREATE TABLE IF NOT EXISTS client_credentials (\n"
    "    id                  INTEGER PRIMARY KEY AUTOINCREMENT,\n"
    "    client_id           INTEGER NOT NULL,\n"
    "    credential_type     TEXT    NOT NULL DEFAULT 'DBD',\n"
    "    registration_number TEXT,\n"
    "    login_id            TEXT,\n"
    "    username            TEXT,\n"
    "    secret_value        TEXT    NOT NULL,\n"
    "    portal_url          TEXT,\n"
    "    notes               TEXT,\n"
    "    is_favorite         INTEGER NOT NULL DEFAULT 0,\n"
    "    created_at          TEXT    NOT NULL DEFAULT (datetime('now', 'localtime')),\n"
    "    updated_at          TEXT    NOT NULL DEFAULT (datetime('now', 'localtime')),\n"
    "    FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE CASCADE\n"
    ");\n"
    "CREATE INDEX IF NOT EXISTS idx_client_credentials_client ON client_credentials(client_id);\n"
    "CREATE INDEX IF NOT EXISTS idx_client_credentials_type ON client_credentials(credential_type);\n"
    "\n"
    "CREATE TABLE IF NOT EXISTS office_credentials (\n"
    "    id              INTEGER PRIMARY KEY AUTOINCREMENT,\n"
    "    account_label   TEXT    NOT NULL,\n"
    "    login_id        TEXT,\n"
    "    email           TEXT,\n"
    "    secret_value    TEXT    NOT NULL,\n"
    "    system_type     TEXT    NOT NULL DEFAULT 'Email',\n"
    "    portal_url      TEXT,\n"
    "    contact_id      INTEGER,\n"
    "    notes           TEXT,\n"
    "    is_favorite     INTEGER NOT NULL DEFAULT 0,\n"
    "    created_at      TEXT    NOT NULL DEFAULT (datetime('now', 'localtime')),\n"
    "    updated_at      TEXT    NOT NULL DEFAULT (datetime('now', 'localtime')),\n"
    "    FOREIGN KEY (contact_id) REFERENCES office_contacts(id) ON DELETE SET NULL\n"
    ");\n"
    "CREATE INDEX IF NOT EXISTS idx_office_credentials_label ON office_credentials(account_label);\n"
    "CREATE INDEX IF NOT EXISTS idx_office_credentials_type ON office_credentials(system_type);\n"
    "\n"
    "CREATE TABLE IF NOT EXISTS notebook_entries (\n"
    "    id              INTEGER PRIMARY KEY AUTOINCREMENT,\n"
    "    entry_type      TEXT    NOT NULL DEFAULT 'general',\n"
    "    title           TEXT    NOT NULL,\n"
    "    body            TEXT,\n"
    "    entry_date      TEXT    NOT NULL,\n"
    "    client_id       INTEGER,\n"
    "    author          TEXT,\n"
    "    follow_up_date  TEXT,\n"
    "    is_pinned       INTEGER NOT NULL DEFAULT 0,\n"
    "    global_id       TEXT UNIQUE,\n"
    "    deleted_at      TEXT,\n"
    "    created_at      TEXT    NOT NULL DEFAULT (datetime('now', 'localtime')),\n"
    "    updated_at      TEXT    NOT NULL DEFAULT (datetime('now', 'localtime')),\n"
    "    FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE SET NULL\n"
    ");\n"
    "CREATE INDEX IF NOT EXISTS idx_notebook_entries_date ON notebook_entries(entry_date);\n"
    "CREATE INDEX IF NOT EXISTS idx_notebook_entries_type ON notebook_entries(entry_type);\n"
)
