SCHEMA_SQL_PART_1 = (
    "    id             INTEGER PRIMARY KEY AUTOINCREMENT,\n"
    "    client_id      INTEGER,\n"
    "    document_type  TEXT    NOT NULL,\n"
    "    expiry_date    TEXT,\n"
    "    amount         TEXT,\n"
    "    payment_date   TEXT,\n"
    "    start_date     TEXT,\n"
    "    progress       TEXT,\n"
    "    paid           INTEGER NOT NULL DEFAULT 0,\n"
    "    file_name      TEXT,\n"
    "    file_path      TEXT,\n"
    "    completed_at   TEXT,\n"
    "    created_at     TEXT    NOT NULL DEFAULT (datetime('now', 'localtime')),\n"
    "    FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE SET NULL\n"
    ");\n"
    "\n"
    "CREATE TABLE IF NOT EXISTS courier_logs (\n"
    "    id               INTEGER PRIMARY KEY AUTOINCREMENT,\n"
    "    client_id        INTEGER,\n"
    "    task_id          INTEGER,\n"
    "    tracking_number  TEXT,\n"
    "    driver_name      TEXT,\n"
    "    date_sent        TEXT,\n"
    "    destination      TEXT,\n"
    "    notes            TEXT,\n"
    "    created_at       TEXT    NOT NULL DEFAULT (datetime('now', 'localtime')),\n"
    "    FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE SET NULL,\n"
    "    FOREIGN KEY (task_id)   REFERENCES tasks(id)   ON DELETE SET NULL\n"
    ");\n"
    "\n"
    "CREATE TABLE IF NOT EXISTS client_months (\n"
    "    id         INTEGER PRIMARY KEY AUTOINCREMENT,\n"
    "    client_id  INTEGER NOT NULL,\n"
    "    month_key  TEXT    NOT NULL,\n"
    "    status     TEXT    NOT NULL DEFAULT 'open'\n"
    "               CHECK (status IN ('open', 'in_progress', 'closed')),\n"
    "    note       TEXT,\n"
    "    updated_at TEXT    NOT NULL DEFAULT (datetime('now', 'localtime')),\n"
    "    UNIQUE (client_id, month_key),\n"
    "    FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE CASCADE\n"
    ");\n"
    "\n"
    "CREATE TABLE IF NOT EXISTS renewal_items (\n"
    "    id            INTEGER PRIMARY KEY AUTOINCREMENT,\n"
    "    client_id     INTEGER NOT NULL,\n"
    "    template_name TEXT    NOT NULL DEFAULT 'Visa Renewal',\n"
    "    item          TEXT    NOT NULL,\n"
    "    due_days      INTEGER NOT NULL DEFAULT 0,\n"
    "    done          INTEGER NOT NULL DEFAULT 0,\n"
    "    done_at       TEXT,\n"
    "    created_at    TEXT    NOT NULL DEFAULT (datetime('now', 'localtime')),\n"
    "    UNIQUE (client_id, template_name, item),\n"
    "    FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE CASCADE\n"
    ");\n"
    "\n"
    "CREATE TABLE IF NOT EXISTS checklist_templates (\n"
    "    id         INTEGER PRIMARY KEY AUTOINCREMENT,\n"
    "    name       TEXT    NOT NULL,\n"
    "    item       TEXT    NOT NULL,\n"
    "    due_days   INTEGER NOT NULL DEFAULT 0,\n"
    "    position   INTEGER NOT NULL DEFAULT 0\n"
    ");\n"
    "\n"
    "CREATE TABLE IF NOT EXISTS snippet_versions (\n"
    "    id         INTEGER PRIMARY KEY AUTOINCREMENT,\n"
    "    created_at TEXT    NOT NULL DEFAULT (datetime('now', 'localtime')),\n"
    "    note       TEXT,\n"
    "    snapshot   TEXT    NOT NULL\n"
    ");\n"
    "\n"
)
