"""Re-export surface for config: licensing (group B).

Imported by ``config/__init__.py`` via `from ._exports_b import *`;
``__all__`` pins the exact public names so the surface is unchanged.
"""

from skyadmin_pro.config.licensing import (
    API_BASE_URL,
    LEGAL_DISCLAIMER_SHORT,
    LEGAL_DISCLAIMER_TEXT,
    LEGAL_LICENSE_TEXT,
    MOBILE_VIEWER_URL,
    PRICING_OVER_YEAR_TEXT,
    PRICING_TIERS,
    REVOCATION_URL,
    SETTING_DATA_SYNC_ENABLED,
    SETTING_DRIVE_FILES_ENABLED,
    SETTING_LICENSE_DRIVE_FILES,
    SETTING_LICENSE_MAX_DEVICES,
    SETTING_LICENSE_ORG_ID,
    SETTING_LICENSE_SYNC,
    SETTING_LICENSE_WEB,
    SETTING_MOBILE_VAULT_KEY,
    SETTING_MOBILE_VAULT_SALT,
    SETTING_MOBILE_VAULT_VERIFIER,
    SETTING_SYNC_AUTO_INTERVAL,
    SETTING_SYNC_LAST_PULL,
    SETTING_SYNC_LAST_PUSH,
)

__all__ = [
    "API_BASE_URL",
    "LEGAL_DISCLAIMER_SHORT",
    "LEGAL_DISCLAIMER_TEXT",
    "LEGAL_LICENSE_TEXT",
    "MOBILE_VIEWER_URL",
    "PRICING_OVER_YEAR_TEXT",
    "PRICING_TIERS",
    "REVOCATION_URL",
    "SETTING_DATA_SYNC_ENABLED",
    "SETTING_DRIVE_FILES_ENABLED",
    "SETTING_LICENSE_DRIVE_FILES",
    "SETTING_LICENSE_MAX_DEVICES",
    "SETTING_LICENSE_ORG_ID",
    "SETTING_LICENSE_SYNC",
    "SETTING_LICENSE_WEB",
    "SETTING_MOBILE_VAULT_KEY",
    "SETTING_MOBILE_VAULT_SALT",
    "SETTING_MOBILE_VAULT_VERIFIER",
    "SETTING_SYNC_AUTO_INTERVAL",
    "SETTING_SYNC_LAST_PULL",
    "SETTING_SYNC_LAST_PUSH",
]
