"""Re-export surface for config: checklists, documents, office (group A).

Imported by ``config/__init__.py`` via `from ._exports_a import *`;
``__all__`` pins the exact public names so the surface is unchanged.
"""

from skyadmin_pro.config.checklists import (
    CHECKLIST_TEMPLATES,
    COMPANY_SETUP_CHECKLIST_ITEMS,
    CSH_RENEWAL_CHECKLIST_ITEMS,
    GENERAL_RENEWAL_CHECKLIST_ITEMS,
    GENERAL_RENEWAL_TEMPLATE_NAME,
    PASSPORT_RENEWAL_CHECKLIST_ITEMS,
    RENEWAL_CHECKLIST_ITEMS,
    RENEWAL_TEMPLATE_MAP,
    VAT_ADDRESS_CHECKLIST_ITEMS,
    VO_RENEWAL_CHECKLIST_ITEMS,
    WORK_PERMIT_RENEWAL_CHECKLIST_ITEMS,
    renewal_template_for,
)
from skyadmin_pro.config.documents import (
    FINANCIAL_DOC_CATEGORIES,
    FINANCIAL_DOC_FOLDER_MAP,
    FINANCIAL_DOC_SUBCATEGORIES,
    IMAGE_SUFFIXES,
    PDF_SUFFIX,
)
from skyadmin_pro.config.office import (
    CLIENT_CREDENTIAL_TYPES,
    CONTACT_CATEGORIES,
    NOTEBOOK_ENTRY_TYPES,
    OFFICE_SYSTEM_TYPES,
    OWNER_BUSINESS_NAME,
    OWNER_EMAIL,
    OWNER_WHATSAPP_DISPLAY,
    OWNER_WHATSAPP_NUMBER,
    VAULT_CATEGORIES,
)

__all__ = [
    "CHECKLIST_TEMPLATES",
    "CLIENT_CREDENTIAL_TYPES",
    "COMPANY_SETUP_CHECKLIST_ITEMS",
    "CONTACT_CATEGORIES",
    "CSH_RENEWAL_CHECKLIST_ITEMS",
    "FINANCIAL_DOC_CATEGORIES",
    "FINANCIAL_DOC_FOLDER_MAP",
    "FINANCIAL_DOC_SUBCATEGORIES",
    "GENERAL_RENEWAL_CHECKLIST_ITEMS",
    "GENERAL_RENEWAL_TEMPLATE_NAME",
    "IMAGE_SUFFIXES",
    "NOTEBOOK_ENTRY_TYPES",
    "OFFICE_SYSTEM_TYPES",
    "OWNER_BUSINESS_NAME",
    "OWNER_EMAIL",
    "OWNER_WHATSAPP_DISPLAY",
    "OWNER_WHATSAPP_NUMBER",
    "PASSPORT_RENEWAL_CHECKLIST_ITEMS",
    "PDF_SUFFIX",
    "RENEWAL_CHECKLIST_ITEMS",
    "RENEWAL_TEMPLATE_MAP",
    "VAT_ADDRESS_CHECKLIST_ITEMS",
    "VAULT_CATEGORIES",
    "VO_RENEWAL_CHECKLIST_ITEMS",
    "WORK_PERMIT_RENEWAL_CHECKLIST_ITEMS",
    "renewal_template_for",
]
